use 5.006;
use ExtUtils::MakeMaker;
# See lib/ExtUtils/MakeMaker.pm for details of how to influence
# the contents of the Makefile that is written.
WriteMakefile(
    NAME              => 'Acme::void',
    VERSION_FROM      => 'void.pm', # finds $VERSION
    PREREQ_PM         => {
	Want => 0.01,
    }, # e.g., Module::Name => 1.1
    ($] >= 5.005 ?     ## Add these new keywords supported since 5.005
      (ABSTRACT_FROM  => 'void.pm', # retrieve abstract from module
       AUTHOR         => 'Okamoto RYO <ryo@aquahill.net>') : ()),
);
